// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2aLNK8TxBL1vZcIz5BmImjPBQqbuVmk',
    appId: '1:895013217342:web:fa471cf04cf0b88dd2dd6f',
    messagingSenderId: '895013217342',
    projectId: 'flutter-shop-affed',
    authDomain: 'flutter-shop-affed.firebaseapp.com',
    storageBucket: 'flutter-shop-affed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIOfAwPoTm72kA8uuy62ZWT68bib3GjNA',
    appId: '1:895013217342:android:9e00a8957bd37a4cd2dd6f',
    messagingSenderId: '895013217342',
    projectId: 'flutter-shop-affed',
    storageBucket: 'flutter-shop-affed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUJDyaoIN2V_QONnd10RWMk4LQTQ-AQ0',
    appId: '1:895013217342:ios:3fe3d3b4485b0844d2dd6f',
    messagingSenderId: '895013217342',
    projectId: 'flutter-shop-affed',
    storageBucket: 'flutter-shop-affed.firebasestorage.app',
    iosBundleId: 'com.tuempresa.flutterShop',
  );
}
